version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config.py:/app/config.py
      - ./instance:/app/instance
      - ./static:/app/static
    environment:
      - FLASK_DEBUG=0
    restart: unless-stopped