version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config.py:/app/config.py
      - ./instance:/app/instance
      - ./static:/app/static
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    # Run in interactive mode for debugging
    tty: true
    stdin_open: true