version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./config.py:/app/config.py
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped